version: '3.8'

services:
  chess-platform:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_ATLAS_URI=${MONGODB_ATLAS_URI}
      - JWT_SECRET=${JWT_SECRET}
      - STOCKFISH_PATH=/usr/bin/stockfish
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
